config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only:[:show,:index,:edit,:update]
  root to:  "homes#top"
 get "/homes/about" => "homes/about"
  resources :books, only:[:index,:show,:create,:edit,:update,:destroy] do
    resource :favorites, only:[:create,:destroy]
  resources :book_comments, only:[:create, :destroy]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  validates :name, uniqueness: true, length: { in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image

  def favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!,except: [:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
   render :index
  end

  def destroy
   @book = Book.find(params[:book_id])
   BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
   render :index

  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def index
    @books =Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def create
    @book =Book.new(book_params)
    @book.user_id = current_user.id
   if @book.save
     flash[:notice]="successfully"
    redirect_to book_path(@book.id)
   else
     render :show
   end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user != @book.user
      redirect_to user_path(current_user)
    end
  end

  def update
    @book = Book.find(params[:id])
   if  @book.update(book_params)
     flash[:notice]="successfully"
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController


def create
  @book = Book.find(params[:book_id ])
  favorite = current_user.favorites.new(book_id: @book.id)
  favorite.save
end

def destroy
  @book = Book.find(params[:book_id ])
  favorite = current_user.favorites.find_by(book_id: @book.id)
  favorite.destroy
end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books =@user.books
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user= User.find(params[:id])
   if @user.update(user_params)
     flash[:notice]= "successfully"
    redirect_to user_(@user.id)
   else
     render :edit
   end
  end


  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model: [book, book_comment])  do |f| %>
      <div class= "form-group">
        <label for= "inputcomment"><h4>New comment</h4></label>
        <%= f.text_area :comment ,id:"inputcomment", class: "form-control" %>
      </div>
        <%= f.submit 'Create Comment', class: "btn btn-success" %>
       <% end %>
     </div>

app/views/book_comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
    <tr>
        <th><%= attachment_image_tag book_comment.user,:profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></br>
            <%= book_comment.user.name %></th>
　        <td><%= book_comment.comment %></td>
          <td> <%= book_comment.created_at.strftime('%Y/%m/%d') %></td>
          <% if book_comment.user === current_user %>
          <td><%=link_to "Delete", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger"%></td>
          <% end %>
    </tr>
<% end %>

app/views/book_comments/ndex.js.erb
$("#comment-area").html("<%= j(render 'book_comments/index', book: @book) %>");
$("textarea").val('');

app/views/books/_form.html.erb
<% if book.errors.any? %>
   <%= book.errors.count %> error
   <% book.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
  <% end %>
  <h3>New book</h3>
    <%= form_with model: book, local: true do |f| %>
      <div class = "form-group">
      <label for="inputtitle" >Title</label>
        <%= f.text_field :title,id:"inpttitle", class: "form-control" %>
      </div>
      <div class = "form-group">
      <label for="inputbody">Opinion</label>
        <%=f.text_area :body,id:"inptbody", class: "form-control" %>
       </div>
        <%=f.submit 'Create Book', class: "brn btn-success" %>
     <% end %>

app/views/books/edit.html.erb
<main>
  <% if @book.errors.any? %>
   <%= @book.errors.count %> error
   <% @book.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
  <% end %>


  <div class ="container mt-5">
    <div class ="row">
      <div class ="col-md-8 mx-auto">
        <h3>Editing Book</h3>
        <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for= "inputtitle">Title</label>
          <%=f.text_field :title, id:"inputtitle", class: "form-control" %>
        </div>
        <div class="form-group">
          <label for= "inputbody">Opinion</label>
          <%=f.text_area :body, id:"inputbody", class: "form-control" %>
        </div>
          <%=f.submit 'Update Book', class: "btn btn-success" %>
        <% end %>
        <span><%= link_to "Show |", book_path(@book.id) %></span>
        <span><%= link_to "Back", books_path %></span>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>

  <div class ="container mt-5">
    <div class="row">
      <div class="col-md-3">
     <%= render 'users/userinfo', user: @user %>

     <%= render 'form', book: @book %>
     </div>

    <div class="col-md-8">
    <table class="table">
    <h3>Books</h3>
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">title</th>
          <th scope="col">Opinion</th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
      <tr>
        <th scope="row"><%= attachment_image_tag book.user,:profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></th>
        <td><%= link_to  book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>

       <td id= "favorite-btn-<%= book.id %>">
         <%= render 'favorites/favorite-btn',  book: book %>
       </td>

        <td> <i class="far fa-comment"></i></br><%=link_to  "#{book.book_comments.count}", book_path(book.id) %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
 </div>
 </div>
</main>

app/views/books/show.html.erb
<main>
  <div class ="container mt-5">
    <div class="row">
      <div class="col-md-3">
       <%= render 'users/userinfo', user: @user %>

       <%= render 'form', book: @book_new %>
     </div>

    <div class="col-md-8">
    <table class="table">
    <h3>Book detail</h3>
      <tbody>
        <tr>
          <td><%= attachment_image_tag @book.user,:profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></br>
          <%= @book.user.name %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>

          <td id= "favorite-btn-<%= @book.id %>">
         <%= render 'favorites/favorite-btn', book: @book %>
         </td>

          <% if @user.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
          <td><%= link_to "Delete",book_path(@book.id), method: :delete,
            data: {confirm: "Are you Sure?"}, class: "btn btn-danger"%></td>
          <% end %>
        </tr>
      </tbody>
     </table>
     <table class="table">
      <h4>Comment  <%= @book.book_comments.count %></h4>
      <tbody id="comment-area">

          <%= render 'book_comments/index', book: @book  %>

      </tbody>
     </table>

      <div id="new-coment">
     <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
    </div>

  </div>
  </div>
</main>

app/views/favorites/_favorite-btn.html.erb
<% if user_signed_in? %>
    <% if current_user.favorited?(book) %>
        <%=link_to book_favorites_path(book), class: "like-link", method: :delete, remote: true do  %>
            <i class="fa fa-heart unlike-btn" style="color: #e54747;">
            <%=book.favorites.count %>
            </i>
    <% end %>
    <% else %>
        <%=link_to book_favorites_path(book), class: "like-link", method: :post, remote: true do  %>
            <i class="fa fa-heart like-btn" style="color: #808080;">
            <%=book.favorites.count%>
            </i>
    <% end %>
    <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite-btn-<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class= "container">
      <div class= "row">
        <div class ="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <h4 class="nav-bar-brand" style="color:#fff;">Bookers02</h4>


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
          aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="#navbarNavDropdown">
            <ul class="navbar-nav  ml-auto">
              <% if user_signed_in? %>
                <li>
                    <%=link_to user_path(current_user.id) do %>
                   <i class= "fas fa-home nav-link text-light">
                     <span >Home</span>
                      </i>
                   <% end %>
                </li>
                <li>
                    <%=link_to users_path do %>
                    <i class="fas fa-users nav-link text-light">
                     <span>Users</span>
                      </i>
                    <% end %>
                </li>
                <li>
                    <%= link_to  books_path do %>
                    <i class="fas fa-book-open nav-link text-light">
                     <span>Books</span>
                      </i>
                    <% end %>
                </li>
                <li>
                    <%= link_to  destroy_user_session_path, method: :delete  do %>
                    <i class="fas fa-sign-out-alt nav-link text-light">
                     <span>logout</span>
                      </i>
                    <% end %>
                </li>
            　 <% else %>
            　 <li>
                    <%=link_to root_path do %>
                   <i class= "fas fa-home nav-link text-light">
                     <span >Home</span>
                      </i>
                   <% end %>
                </li>
                <li>
                  <%=link_to homes_about_path do%>
                  <i class="fas fa-link nav-link text-light">
                    <span>About</span>
                  </i>
                  <% end %>
                </li>
                <li>
                   <%= link_to  new_user_registration_path do %>
                   <i class="fas fa-user-plus nav-link text-light">
                    <span>sign_up</span>
                   </i>
                   <% end %>
                </li>
                <li>
                  <%= link_to user_session_path do %>
                  <i class="fas fa-sign-in-alt nav-link text-light">
                    <span>sign_in</span>
                  </i>
                  <% end %>
                </li>
              <% end %>
             </ul>
          </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers02</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_userinfo.html.erb
 <table class="table">
        <h3>User info</h3>
        <%= attachment_image_tag user,:profile_image, :fill, 60 , 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <thead>
          <tr>
            <th scope="col">name</th>
            <th scope="col"><%=user.name %></th>
          </tr>
          <tr>
            <th scope="col">introdcution</th>
            <th scope="col"><%=user.introduction %></th>
          </tr>
        </thead>
        <tr scope="col">
         <% if current_user.id ==  user.id %>
         <td><%=link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block  fas fa-user-cog" %></td>
         <% else %>
         <td><%=link_to "", user_path(current_user), class: "btn btn-outline-secondary btn-block  fas fa-user-cog" %></td>
         <% end %>
        </tr>
      </table>

app/views/users/edit.html.erb
<main>
  <% if @user.errors.any? %>
   <%= @user.errors.count %> error
   <% @user.errors.full_messages.each do |message| %>
   <%= message %>
   <% end %>
  <% end %>

  <div class ="container mt-5">
    <div class ="row">
      <div class ="col-md-8 mx-auto">
        <h3>User info</h3>
        <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label for= "inputname">Name</label>
          <%=f.text_field :name, autofocus: true, id:"inputname", class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Image</label>
          <%=f.attachment_field :profile_image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for= "inputintroduction">Introduction</label>
          <%=f.text_area :introduction, id:"inputintroduction", class: "form-control" %>
        </div>
          <%=f.submit 'Update User', class: "btn btn-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <div class ="container mt-5">
    <div class="row">
      <div class="col-md-3">
       <%= render 'userinfo', user: @user %>

       <%= render 'books/form', book: @book %>
     </div>

     <div class="col-md-8">
     <table class="table">
     <h3>Users</h3>
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">image</th>
          <th scope="col">name</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
      <tr>
        <th scope="row"> <%= attachment_image_tag user,:profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></th>
        <td><%= user.name %></td>
        <td><%=link_to "Show", user_path(user.id) %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </div>
  </div>
</main>

app/views/users/show.html.erb
 <main>
  <div class ="container mt-5">
    <div class="row">
      <div class="col-md-3">
        <%= render 'userinfo', user: @user %>

        <%= render 'books/form', book: @book %>
     </div>


    <div class="col-md-8">
    <table class="table">
    <h3>Books</h3>
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">title</th>
          <th scope="col">Opinion</th>
        </tr>
      </thead>
      <tbody>
      <% @books.each do |book| %>
      <tr>
        <th scope="row"></th>
        <td><%=link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><i class="fas fa-heart"></i></br><%=book.favorites.count %></td>
        <td><i class="far fa-comment"></i></br><%=link_to  "#{book.book_comments.count}", book_path(book.id) %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
 </div>
 </div>
</main>